version: '3.5'
services:
  # This runs the database that everything else connects to
  db:
    container_name: scrutinize_db
    image: postgres:12.8
    env_file:
      - .env.docker
    working_dir: /
    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - default
    command:
      postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/var/lib/postgresql/data/logs -c
      log_rotation_age=60 -c log_truncate_on_rotation=on -c log_filename=server_log.hour.%H%M

  # This runs local AWS services for development
  aws:
    container_name: scrutinize_aws
    image: localstack/localstack
    environment:
      SERVICES: s3,sqs
    ports:
      - '4566:4566'
    volumes:
      - ./.localstack:/docker-entrypoint-initaws.d
networks:
  default:
    # No metadata required right now.

volumes:
  # Postgres' data
  db-volume:
