name: Node CI

on:
  push:
    branches-ignore:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      CI: true
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
      - name: test
        run: yarn test
